#!/usr/bin/env bash

echo "Running pre-push lint check..."

set -eum

git diff --name-only HEAD origin/"$(git rev-parse --abbrev-ref HEAD)" | grep '\.kt[s"]\?$' | xargs ktlint --android --relative .
if [ $? -ne 0 ]; then exit 1; fi
