#!/usr/bin/env bash

echo "Running pre-commit lint check..."

set -eum

git diff --name-only --cached --relative | grep '\.kt[s"]\?$' | xargs ktlint --android --relative .
if [ $? -ne 0 ]; then exit 1; fi