#!/usr/bin/env bash

echo "Running pre-push lint check..."
OUTPUT="/tmp/detekt-$(date +%s)"

./support/scripts/lint >"${OUTPUT}"

EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  cat "$OUTPUT"
  rm "$OUTPUT"
  echo "-----------------------------------------------------"
  echo "Lint failed. Fix the detekt issue to push the changes"
  echo "-----------------------------------------------------"
  exit $EXIT_CODE
fi
rm "$OUTPUT"