#!/usr/bin/env bash

set -xeu
set -o pipefail

function finish() {
  printf "\n---Finished Running Instrumented Tests---\n"
}

trap finish EXIT

# Run all unit tests inside the instrumented-test-collector-library Module
./gradlew clean connectedDebugAndroidTest