#!/usr/bin/env bash

set -xeu
set -o pipefail

function finish() {
  printf "\n---Finished Running All Instrumented Tests---\n"
}

trap finish EXIT

# Run all instrumented tests of the project
./gradlew clean connectedDebugAndroidTest