#!/usr/bin/env bash

set -xeu
set -o pipefail

function finish() {
  printf "\n---Finished Running SDK Instrumented Tests---\n"
}

trap finish EXIT

# Run all instrumented tests inside the instrumented-test-collector Module
./gradlew clean :collector:instrumented-test-collector:connectedCheck