#!/usr/bin/env bash

set -xeu
set -o pipefail

function finish() {
  printf "\n---Finished Running SDK Unit Tests---\n"
}

trap finish EXIT

# Run all unit tests inside the test-collector module
./gradlew clean :collector:instrumented-test-collector:testDebug
./gradlew clean :collector:test-data-uploader:test
./gradlew clean :collector:unit-test-collector:test